"""Rules engine models."""

from __future__ import annotations

from dataclasses import dataclass, field

from app.inventory.models import InventorySummary
from app.zones.models import ZoneValidationResult


@dataclass(frozen=True, slots=True)
class ExpectedItem:
    """Expected inventory for a specific zone."""

    class_name: str
    min_count: int = 0
    max_count: int | None = None
    target_count: int | None = None


@dataclass(frozen=True, slots=True)
class ZoneInventoryExpectation:
    """Expected inventory configuration for one zone."""

    zone_id: str
    items: list[ExpectedItem] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class RuleEvent:
    """Business event generated by the rules engine."""

    event_type: str
    severity: str
    zone_id: str | None
    class_name: str | None
    message: str
    details: dict[str, object] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class RulesEvaluationResult:
    """Evaluation result for a frame."""

    frame_id: str
    timestamp: str
    source: str
    events: list[RuleEvent] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class RulesContext:
    """All inputs required to evaluate rules."""

    inventory: InventorySummary
    zone_validation: ZoneValidationResult

