"""LLM request and response models."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class LlmRequest:
    """JSON-only request sent to the LLM client."""

    summary: dict[str, object]
    prompt: str | None = None


@dataclass(frozen=True, slots=True)
class LlmResponse:
    """Textual response generated by an LLM."""

    analysis: str
    raw: dict[str, object] = field(default_factory=dict)

